url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog

title: Mind the Brain
description: Mózgi, nauka, technologia, Python. <br>I jeszcze trochę mózgów.
description-en: Brains, science, technology, Python. <br>And some more brains.
logo: blog_logo.svg
locale: pl_PL
excerpt_separator: <!-- more -->

background:
  home: assets/images/backgrounds/pillars.jpg
  posts: assets/images/backgrounds/neuron2.jpg

sass:
  sass_dir: _sass

permalink: /:categories/:year/:month/:day/:title
future: true
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
  input:            GFM

# Google Analytics
google-analytics:   UA-90696100-1

# Social Links
twitter:            mkoculak
github:             mkoculak
gscholar:           lS4QVYwAAAAJ
orcid:              0000-0002-8839-2365

include: [_pages]